# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8834953619cbab9434402c996b92e298e97cf93cd22a810e1bd3a78c83c32bb77d0d29704bd7a2e562f58ad7e24f853c0086a80e4fc2650b95c025087503714b

test:
  secret_key_base: 7d31f0ccd020d5870c48d122cada78511eee9e0838bfe33cdfada284fb693aa018cd3fcbb7e4529e868bd58400600736504f66f607f4ae93e069a9d85f82be08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
